/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as TransactionsIdRouteImport } from './routes/transactions/$id'
import { Route as SettingsSyncRouteImport } from './routes/settings/sync'
import { Route as SettingsPrinterRouteImport } from './routes/settings/printer'
import { Route as ProductsBarcodeRouteImport } from './routes/products/$barcode'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/settings/sync',
  path: '/settings/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrinterRoute = SettingsPrinterRouteImport.update({
  id: '/settings/printer',
  path: '/settings/printer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBarcodeRoute = ProductsBarcodeRouteImport.update({
  id: '/products/$barcode',
  path: '/products/$barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$barcode': typeof ProductsBarcodeRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$barcode': typeof ProductsBarcodeRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$barcode': typeof ProductsBarcodeRoute
  '/settings/printer': typeof SettingsPrinterRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/success'
    | '/products/$barcode'
    | '/settings/printer'
    | '/settings/sync'
    | '/transactions/$id'
    | '/cart/'
    | '/checkout/'
    | '/products/'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/success'
    | '/products/$barcode'
    | '/settings/printer'
    | '/settings/sync'
    | '/transactions/$id'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/checkout/success'
    | '/products/$barcode'
    | '/settings/printer'
    | '/settings/sync'
    | '/transactions/$id'
    | '/cart/'
    | '/checkout/'
    | '/products/'
    | '/settings/'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsBarcodeRoute: typeof ProductsBarcodeRoute
  SettingsPrinterRoute: typeof SettingsPrinterRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/printer': {
      id: '/settings/printer'
      path: '/settings/printer'
      fullPath: '/settings/printer'
      preLoaderRoute: typeof SettingsPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$barcode': {
      id: '/products/$barcode'
      path: '/products/$barcode'
      fullPath: '/products/$barcode'
      preLoaderRoute: typeof ProductsBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsBarcodeRoute: ProductsBarcodeRoute,
  SettingsPrinterRoute: SettingsPrinterRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
